name: Matrix Demo
on: push
jobs:
    build:
      continue-on-error: true
      strategy:
        matrix:
          node-version: [12, 14, 16]
          operation-system: [ubuntu-latest, windows-latest]
          include:
            - node-version: 12
              operation-system: ubuntu-latest
            - node-version: 14
              operation-system: ubuntu-latest
            - node-version: 16
              operation-system: ubuntu-latest
            - node-version: 12
              operation-system: windows-latest
            - node-version: 14
              operation-system: windows-latest
            - node-version: 16
              operation-system: windows-latest
            - node-version: 18
              operation-system: windows-latest
      runs-on: ${{ matrix.operation-system }}
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NOdeJS
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}       
        - name: Install dependencies
          run: npm ci
        - name: Build Project
          run: npm run build